---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dex-cert
  namespace: image-rbac-proxy
spec:
  isCA: true
  subject:
    organizations:
      - konflux
  ipAddresses:
  - IP
  issuerRef:
    kind: ClusterIssuer
    name: self-signed-cluster-issuer
  secretName: dex-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: image-rbac-proxy-cert
  namespace: image-rbac-proxy
spec:
  isCA: true
  subject:
    organizations:
      - konflux
  ipAddresses:
  - IP
  issuerRef:
    kind: ClusterIssuer
    name: self-signed-cluster-issuer
  secretName: proxy-tls
