apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: image-rbac-proxy
resources:
- ../base
- secret.yaml
- certificate.yaml

configMapGenerator:
  - name: dex
    files:
      - dex-config.yaml

patches:
- path: configmap.yaml
- path: proxy-service.yaml
  target:
    name: image-rbac-proxy
    kind: Service
    version: v1
- path: dex-service.yaml
  target:
    name: dex
    kind: Service
    version: v1
